### ISSUE TITLE
Upload PDFs to database

### ISSUE THREAD

**Issue by aashutosh-samagra** [ChatWithPDF/bff#6]
JSON to be added

**Comment by Amruth-Vamshi** [comment]
@GautamR-Samagra 

curl to upload PDF
```
curl --location 'https://bff.chatwithpdf.aitools.samagra.io/pdf/upload' \
--form 'file=@"/Users/amruthbatta/Desktop/ilovepdf_split/dafe_schemes-1.pdf"' \
--form 'userId="40a7b828-5a70-403d-94de-80e921d719ff"'
```

**Comment by aashutosh-samagra** [comment]
Org Policy PDFs = https://drive.google.com/drive/folders/1LZ7AB7cYlRwC2VmOXixQB9KXAfPv3Sge?usp=sharing

PDF Type JSON = https://drive.google.com/file/d/1V7xgfvCHgmiZfN5L_V29dhbnhBuir9Vg/view?usp=drive_link


PDF Type definition 
1. "simple" - only text
2. "simplewithlinks" - text with hyperlinks
3. "1 table" - text, hyperlinks and 1 table in the PDF
4. "complex" - text, hyperlinks, tables and images

**Comment by Gautam-Rajeev** [comment]
@Amruth-Vamshi  can you provide me the curl for the updating csv's instead of pdfs ?
